#!/bin/bash

pushd $1 > /dev/null
out=$(pwd)/../../out/$1

# Ensure there is an output directory ready
if [ -d $out ]; then
	rm -rf $out
fi

mkdir $out

# Make Modrinth and CurseForge packs
packwiz mr export --output $out/Luminary-$1.mrpack
packwiz cf export --output $out/Luminary-$1.zip

# Make Prism auto-updating pack
mkdir $out/auto
cp $(pwd)/../../prism/{.,}* $out/auto 2> /dev/null
cp $(pwd)/../../prism/$1/{.,}* $out/auto 2> /dev/null
sed -i "s/PreLaunchCommand=/PreLaunchCommand=\"\$INST_JAVA\" -jar \"\$INST_DIR\/packwiz-installer-bootstrap.jar\" https:\/\/raw.githubusercontent.com\/newtykins\/luminary\/main\/versions\/$1\/pack.toml/g" $out/auto/instance.cfg
zip $out/Luminary-$1-auto.zip $out/auto/*
rm -rf $out/auto
