#!/bin/bash
../../scripts/outExists.sh

# Make Modrinth and CurseForge packs
packwiz mr export --output out/Luminary-1.19.3-v1.0.mrpack
packwiz cf export --output out/Luminary-1.19.3-v1.0.zip

# Make Prism auto-updating pack
../../scripts/makeAuto.sh 1.19.3
